version: "3.9"
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '3000:80'
    environment:
      PMA_HOST: db
    depends_on:
      - db
  db:
    image: mysql:latest
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: slim_test
      MYSQL_ROOT_PASSWORD: password
  backend:
    volumes:
      - ./backend:/var/www/html/
    build: ./backend
    environment:
      docker: "true"
    ports:
      - "8080:80"
  frontend:
    image: httpd:2.4
    volumes:
      - ./frontend:/usr/local/apache2/htdocs/
    ports:
      - "80:80"
